name: Build Android
on:
  workflow_dispatch:
permissions: write-all
env:
 FILE_NAME: 'Build_${{github.run_number}}' #빌드 파일 이름 전역변수로 세팅
jobs:
  build: 
    name: Unity Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          if [ "$(docker images -q)" != "" ]; then
            docker rmi $(docker images -q)
          fi
          df -h

      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildName: ${{ env.FILE_NAME }}

      - name: Upload Build File
        uses: actions/upload-artifact@v4
        with:
          name: Build-Android
          path: build
